### ➤ Lista todas as salas
GET http://localhost:4004/odata/v4/catalog/Rooms



{"deleted": true}

### DELETE uma Room pelo ID (substitui o guid)
DELETE http://localhost:4004/odata/v4/catalog/Rooms(ID='11111111-1111-1111-1111-111111111111')
Accept: application/json


### ➤ Lista todos os equipamentos
GET http://localhost:4004/odata/v4/catalog/Equipments

### DELETE uma equipamento pelo ID (substitui o guid)
DELETE http://localhost:4004/odata/v4/catalog/Equipments(ID='e1111111-1111-1111-1111-111111111111')
Accept: application/json


### ➤ Lista todas as reservas
GET http://localhost:4004/odata/v4/catalog/Reservations

### DELETE uma reserva pelo ID (substitui o guid)
DELETE http://localhost:4004/odata/v4/catalog/Reservations(ID='11111111-1111-1111-1111-111111111111')
Accept: application/json



### ➤ Lista reservas com detalhe da sala associada
GET http://localhost:4004/odata/v4/catalog/Reservations?$expand=room


### ➤ Criar nova Sala (se quiseres testar CRUD)
POST http://localhost:4004/odata/v4/catalog/Rooms
Content-Type: application/json

{
  "code": "R-301",
  "name": "Sala Teste",
  "capacity": 15,
  "location": "Edifício C"
}


### ➤ Criar Reserva (substituir ROOM_ID com id válido do GET Rooms)
POST http://localhost:4004/odata/v4/catalog/Reservations
Content-Type: application/json

{
  "room_ID": "GUID_DA_TUA_SALA_AQUI",
  "title": "Reunião Teste",
  "startAt": "2025-10-28T09:00:00Z",
  "endAt": "2025-10-28T10:00:00Z",
  "requester": "João",
  "status": "CONFIRMED"
}


### ➤ Ver BD completa com expand
GET http://localhost:4004/odata/v4/catalog/Rooms?$expand=equipments,Reservations
